### ISSUE TITLE
Function name `get_plugin_name()`

### ISSUE THREAD

**Issue by lucianotonet** [Tmeister/wppb-gen-site#4] opened 2015-02-11 00:45 UTC
I think the function name `get_plugin_name()` and the vars `$plugin_name` should not be replaced.
I'm wrong?

**Comment by Tmeister** [comment] 2015-03-28 05:19
No, You are right.

But this is a duplicate of #1 and is already fixed.

**Closed as completed by Tmeister** 2015-03-28 05:19 UTC
